# Generated by Django 5.1.7 on 2025-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('type', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
            ],
        ),
    ]
