# Generated by Django 5.1.7 on 2025-03-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Monitor_Servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('critical_level', models.IntegerField()),
                ('message', models.TextField()),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CPUMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_type', models.CharField(max_length=50)),
                ('connection_settings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiskMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemoryMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('widget_type', models.CharField(max_length=50)),
                ('data_source', models.CharField(max_length=50)),
                ('display_settings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active_alerts', models.ManyToManyField(to='System_Monitor_Servers.alert')),
                ('alert_rules', models.ManyToManyField(to='System_Monitor_Servers.alertrule')),
            ],
        ),
        migrations.CreateModel(
            name='DataCollector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_interval', models.IntegerField()),
                ('servers', models.ManyToManyField(to='System_Monitor_Servers.server')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Monitor_Servers.alertmanager')),
                ('data_collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Monitor_Servers.datacollector')),
                ('data_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Monitor_Servers.datastorage')),
                ('servers', models.ManyToManyField(to='System_Monitor_Servers.server')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('widgets', models.ManyToManyField(to='System_Monitor_Servers.widget')),
            ],
        ),
    ]
