# Generated by Django 5.1.7 on 2025-03-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System_Monitor_Servers', '0005_server_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='date_added',
        ),
    ]
